[package]
name = "mc_tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mc_core = { path = "../mc_core", version = "0.1.0" }
mc_data = { path = "../mc_data", version = "0.1.0" }
mc_tape = { path = "../mc_tape", version = "0.1.0" }
clap = { workspace = true }
postcard = { workspace = true }
ron = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "gen-golden-tapes"
path = "bin/gen_golden_tapes.rs"
