[package]
name = "mc_shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "monte-cristo"
path = "src/main.rs"

[lib]
name = "mc_shell"
path = "src/lib.rs"

[dependencies]
mc_core = { path = "../mc_core", version = "0.1.0" }
mc_data = { path = "../mc_data", version = "0.1.0" }
mc_tape = { path = "../mc_tape", version = "0.1.0" }
macroquad = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
ron = { workspace = true }

[dev-dependencies]
tempfile = "3"
