[package]
name = "mc_shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mc_core = { path = "../mc_core" }
mc_data = { path = "../mc_data" }
mc_tape = { path = "../mc_tape" }
macroquad = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
