[package]
name = "mc_data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mc_core = { path = "../mc_core", version = "0.1.1" }
serde = { workspace = true }
postcard = { workspace = true, features = ["use-std"] }
ron = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }
